---
- name: Get Endpoints
  uri:
    url: "{{ portainer_endpoint }}/endpoints"
    method: GET
    return_content: true
    headers:
      Authorization: Bearer {{ (auth_token.content|from_json).jwt }}
  register: portainer_known_endpoints_raw

- name: Save endpoints as fact
  set_fact:
    portainer_known_endpoints: "{{ portainer_known_endpoints_raw.json | map(attribute='Name') | list }}"

- name: "Show known endpoints"
  debug: msg="{{ portainer_known_endpoints }}"

- name: Define Endpoints
  uri:
    url: "{{ portainer_endpoint }}/endpoints"
    method: POST
    body_format: form-urlencoded
    headers:
      Authorization: "Bearer {{ (auth_token.content|from_json).jwt }}"
    body:
      Name: "{{ item.name }}"
      URL: "{{ item.url }}"
      PublicURL: "{{ item.public_url }}"
      EndpointCreationType: 1
    status_code: 200
  with_items:
    - "{{ endpoints | list }}"
  when: item.name not in portainer_known_endpoints
  register: response
